# Generated by Django 3.1.5 on 2021-01-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('county_name', models.CharField(max_length=30)),
                ('state_code', models.CharField(max_length=30)),
                ('state_name', models.CharField(max_length=30)),
            ],
        ),
    ]
